import json
import os

nb_path = os.path.join('notebook', '03_ml_training_evaluation.ipynb')
with open(nb_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# Cell 37 is the benchmark comparison code cell
cell37_source = [
    "# ==============================================================================\n",
    "# MULTI-MODEL BENCHMARK COMPARISON (TABLE & CHART FOR RESEARCH PAPER)\n",
    "# Evaluates Logistic Regression, Decision Tree, SVM, Random Forest, & Dummy Classifier\n",
    "# ==============================================================================\n",
    "\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.svm import SVC\n",
    "\n",
    "benchmark_models = {\n",
    "    'Logistic Regression': LogisticRegression(random_state=42, class_weight='balanced', max_iter=1000),\n",
    "    'Decision Tree': DecisionTreeClassifier(random_state=42, class_weight='balanced'),\n",
    "    'Support Vector Machine (SVM)': SVC(random_state=42, class_weight='balanced', probability=True),\n",
    "    'Random Forest': rf_b,\n",
    "    'Dummy Classifier': dummy\n",
    "}\n",
    "\n",
    "benchmark_rows = []\n",
    "for name, m in benchmark_models.items():\n",
    "    if name not in ['Random Forest', 'Dummy Classifier']:\n",
    "        m.fit(X_train_b, y_train)\n",
    "    \n",
    "    y_p = m.predict(X_test_b)\n",
    "    \n",
    "    benchmark_rows.append({\n",
    "        'Model': name,\n",
    "        'Accuracy': round(accuracy_score(y_test, y_p), 4),\n",
    "        'Macro Precision': round(precision_score(y_test, y_p, average='macro', zero_division=0), 4),\n",
    "        'Macro Recall': round(recall_score(y_test, y_p, average='macro', zero_division=0), 4),\n",
    "        'Macro F1': round(f1_score(y_test, y_p, average='macro', zero_division=0), 4),\n",
    "        'Weighted Precision': round(precision_score(y_test, y_p, average='weighted', zero_division=0), 4),\n",
    "        'Weighted Recall': round(recall_score(y_test, y_p, average='weighted', zero_division=0), 4),\n",
    "        'Weighted F1': round(f1_score(y_test, y_p, average='weighted', zero_division=0), 4)\n",
    "    })\n",
    "\n",
    "df_benchmark_comp = pd.DataFrame(benchmark_rows)\n",
    "display(df_benchmark_comp)\n",
    "\n",
    "# Export comparison CSV to results/ml/model_comparison.csv\n",
    "comp_csv_out = os.path.join('..', 'results', 'ml', 'model_comparison.csv')\n",
    "if not os.path.exists(os.path.dirname(comp_csv_out)):\n",
    "    comp_csv_out = os.path.join('results', 'ml', 'model_comparison.csv')\n",
    "df_benchmark_comp.to_csv(comp_csv_out, index=False, encoding='utf-8')\n",
    "print(f\"Exported multi-model benchmark comparison to: {comp_csv_out}\")\n",
    "\n",
    "# ==============================================================================\n",
    "# ACADEMIC GROUPED BAR CHART: TEST-SET PERFORMANCE ACROSS MODELS\n",
    "# Source: Exact values from results/ml/model_comparison.csv\n",
    "# ==============================================================================\n",
    "\n",
    "df_chart = pd.read_csv(comp_csv_out)\n",
    "\n",
    "model_display_names = {\n",
    "    'Logistic Regression': 'Logistic\\nRegression',\n",
    "    'Decision Tree': 'Decision\\nTree',\n",
    "    'Support Vector Machine (SVM)': 'Support Vector\\nMachine (SVM)',\n",
    "    'Random Forest': 'Random Forest\\n(Primary)',\n",
    "    'Dummy Classifier': 'Dummy Classifier\\n(Baseline)'\n",
    "}\n",
    "df_chart['Display_Name'] = df_chart['Model'].map(lambda x: model_display_names.get(x, x))\n",
    "\n",
    "metrics = ['Accuracy', 'Macro Precision', 'Macro Recall', 'Macro F1']\n",
    "x = np.arange(len(df_chart))\n",
    "bar_width = 0.18\n",
    "\n",
    "# Academic grayscale tones with distinct hatches for IEEE publication standards\n",
    "styles = [\n",
    "    {'color': '#2b2b2b', 'hatch': '', 'label': 'Accuracy'},\n",
    "    {'color': '#6e6e6e', 'hatch': '///', 'label': 'Macro Precision'},\n",
    "    {'color': '#a8a8a8', 'hatch': '\\\\\\\\', 'label': 'Macro Recall'},\n",
    "    {'color': '#e2e2e2', 'hatch': 'xx', 'label': 'Macro F1'}\n",
    "]\n",
    "\n",
    "fig, ax = plt.subplots(figsize=(11, 6), dpi=300)\n",
    "\n",
    "for i, (m_col, style) in enumerate(zip(metrics, styles)):\n",
    "    offset = (i - 1.5) * bar_width\n",
    "    bars = ax.bar(\n",
    "        x + offset,\n",
    "        df_chart[m_col],\n",
    "        width=bar_width,\n",
    "        label=style['label'],\n",
    "        color=style['color'],\n",
    "        hatch=style['hatch'],\n",
    "        edgecolor='black',\n",
    "        linewidth=0.8,\n",
    "        zorder=3\n",
    "    )\n",
    "    \n",
    "    # Add numerical values above each bar\n",
    "    for bar in bars:\n",
    "        height = bar.get_height()\n",
    "        ax.text(\n",
    "            bar.get_x() + bar.get_width() / 2.0,\n",
    "            height + 0.015,\n",
    "            f'{height:.2f}',\n",
    "            ha='center',\n",
    "            va='bottom',\n",
    "            fontsize=8,\n",
    "            fontweight='medium',\n",
    "            color='black'\n",
    "        )\n",
    "\n",
    "ax.set_title('Comparison of Test-Set Performance Across Machine-Learning Models', fontsize=12, fontweight='bold', pad=15)\n",
    "ax.set_xlabel('Model', fontsize=11, fontweight='semibold', labelpad=10)\n",
    "ax.set_ylabel('Score (0–1)', fontsize=11, fontweight='semibold')\n",
    "ax.set_xticks(x)\n",
    "ax.set_xticklabels(df_chart['Display_Name'], fontsize=9.5)\n",
    "ax.set_ylim(0, 1.05)\n",
    "ax.set_yticks(np.arange(0.0, 1.1, 0.2))\n",
    "\n",
    "# Horizontal grid behind bars\n",
    "ax.yaxis.grid(True, linestyle='--', alpha=0.5, color='#aaaaaa', zorder=0)\n",
    "ax.set_axisbelow(True)\n",
    "\n",
    "# Clean legend\n",
    "ax.legend(\n",
    "    loc='upper left',\n",
    "    bbox_to_anchor=(0.02, 0.98),\n",
    "    frameon=True,\n",
    "    framealpha=0.9,\n",
    "    edgecolor='#888888',\n",
    "    fontsize=9.5\n",
    ")\n",
    "\n",
    "# Clean academic borders\n",
    "ax.spines['top'].set_visible(False)\n",
    "ax.spines['right'].set_visible(False)\n",
    "ax.spines['left'].set_color('#333333')\n",
    "ax.spines['bottom'].set_color('#333333')\n",
    "\n",
    "plt.tight_layout()\n",
    "\n",
    "chart_out_path = os.path.join('..', 'results', 'ml', 'model_comparison_bar_chart.png')\n",
    "if not os.path.exists(os.path.dirname(chart_out_path)):\n",
    "    chart_out_path = os.path.join('results', 'ml', 'model_comparison_bar_chart.png')\n",
    "plt.savefig(chart_out_path, dpi=300, bbox_inches='tight')\n",
    "print(f\"Saved benchmark comparison bar chart to: {chart_out_path}\")\n",
    "plt.show()\n"
]

nb['cells'][37]['source'] = cell37_source

with open(nb_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print(f"Updated {nb_path} with benchmark chart. Cell 37 source updated.")
